# Generated by Django 4.2.1 on 2023-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_address_member_age_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='DateOfJoining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='designation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
